task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# num_classes: 365
# remap_mscoco_category: False

# num_classes: 91
# remap_mscoco_category: False

num_classes: 10
# remap_mscoco_category: True


train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data/datasets/VisDrone/VisDrone2019-DET-train/images/
    ann_file: /data/datasets/VisDrone/VisDrone_COCO/VisDrone2019-DET-train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 224
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFuncion


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data/datasets/VisDrone/VisDrone2019-DET-test-dev/images/
    ann_file: /data/datasets/VisDrone/VisDrone_COCO/VisDrone2019-DET-test-dev.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 224
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion


test_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data/datasets/VisDrone/VisDrone2019-DET-test-dev/images/
    ann_file: /data/datasets/VisDrone/VisDrone_COCO/VisDrone2019-DET-test-dev.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 224
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion
