__include__: [
  '../dataset/visdrone_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_hiera.yml',
]


output_dir: ./output/rtdetrv2_hiera/

#Hiera tiny backbone
Hiera:
  input_size: [1280, 1280]
  embed_dim: 96
  num_heads: 1
  stages: [1, 2, 7, 2]
  pretrained: True
  


HybridEncoder:
  in_channels: [192, 384, 768]
  hidden_dim: 256
  expansion: 0.5

RTDETRTransformerv2:
  num_layers: 3


epoches: 120 

optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.


train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: 117
  collate_fn:
    scales: ~